version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node-modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=kamlesh
      - MONGO_PASSWORD=12345
      - SESSION_SECRET=secret
      
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kamlesh
      - MONGO_INITDB_ROOT_PASSWORD=12345
